DESIGN		:= div
CC		:= g++
LDFLAGS		+= -lm -lsystemc -L$(AUTOESL_ROOT)/$(AUTOESL_ARCH)/tools/systemc/lib
CXXFLAGS	+= -I$(AUTOESL_ROOT)/$(AUTOESL_ARCH)/tools/systemc/include -I$(AUTOESL_ROOT)/include
sim: $(DESIGN)
		./$(DESIGN)
autoesl: $(DESIGN).tcl
		vivado_hls -f $<
hardware: $(DESIGN)_batch.prj/solution1/impl/vhdl/impl.sh
		cd $(DESIGN)_batch.prj/solution1/impl/vhdl; ./impl.sh; cd ../../../../
$(DESIGN): $(DESIGN).o $(DESIGN)_test.o $(DESIGN).h
		$(CC) -o $@ $(filter %.o, $^) $(LDFLAGS)
